
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const POST_START = 'POST_START' ;
export const POST_SUCCESS = 'POST_SUCCESS' ;
export const POST_FAILED = 'POST_FAILED' ;
export const GET_POSTS_START = 'GET_POSTS_START' ;
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS' ;
export const GET_POSTS_FAILED = 'GET_POSTS_FAILED' ;

export const UPDATE_UNCHECKED_POSTS_START = 'UPDATE_UNCHECKED_POSTS_START';
export const UPDATE_UNCHECKED_POSTS_SUCCESS = 'UPDATE_UNCHECKED_POSTS_SUCCESS';
export const UPDATE_UNCHECKED_POSTS_FAILED = 'UPDATE_UNCHECKED_POSTS_FAILED';

export const SET_LAST_LOGIN_START = 'SET_LAST_LOGIN_START';
export const SET_LAST_LOGIN_SUCCESS = 'SET_LAST_LOGIN_SUCCESS';
export const SET_LAST_LOGIN_FAILED = 'SET_LAST_LOGIN_FAILED';

export const INCREMENT_CHECKED_POSTS = 'INCREMENT_CHECKED_POSTS';
export const DECREMENT_CHECKED_POSTS = 'DECREMENT_CHECKED_POSTS';

export const GET_UNCHECKED_POSTS_START = 'GET_UNCHECKED_POSTS_START';
export const GET_UNCHECKED_POSTS_SUCCESS = 'GET_UNCHECKED_POSTS_SUCCESS';
export const GET_UNCHECKED_POSTS_FAILED = 'GET_UNCHECKED_POSTS_FAILED';

export const RESET_THE_STATE = 'RESET_THE_STATE'
