
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const POST_START = 'POST_START' ;
export const POST_SUCCESS = 'POST_SUCCESS' ;
export const POST_FAILED = 'POST_FAILED' ;

export const GET_POSTS_START = 'GET_POSTS_START' ;
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS' ;
export const GET_POSTS_FAILED = 'GET_POSTS_FAILED' ;

export const PUT_POST_TO_SERVER_START = 'PUT_POST_TO_SERVER_START';
export const PUT_POST_TO_SERVER_SUCCESS = 'PUT_POST_TO_SERVER_SUCCESS';
export const PUT_POST_TO_SERVER_FAILED = 'PUT_POST_TO_SERVER_FAILED';

export const UPDATE_CHECKED_POSTS = 'UPDATE_CHECKED_POSTS';

